version: "3"
services:
    gatsby:
        image: gatsby
        container_name: gatsby
        build:
            context: .
            dockerfile: gatsby.dockerfile
        volumes:
            - ./gatsby:/gatsby
        ports:
            - 1990:8000
        networks:
            - wp_gatsby
        command: develop # Options: "develop", "build" or "stage", see entrypoint.
        depends_on:
            - wordpress

    wordpress:
        image: wordpress
        container_name: wordpress
        volumes:
            - ./wp:/var/www/html
        ports:
            - 1980:80
        networks:
            - wp_gatsby
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        networks:
            - wp_gatsby
        depends_on:
            - db
        ports:
            - 1970:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: wordpress

    db:
        image: mariadb
        container_name: mariadb
        volumes:
            - ./wp_data:/var/lib/mysql
        networks:
            - wp_gatsby
        environment:
            MYSQL_ROOT_PASSWORD: wordpress

networks:
    wp_gatsby:
